// @formatter:off
// ignore_for_file: constant_identifier_names

const Map<String, String> translations_en_US = {
  'Account info': 'Account info',
  'Add note': 'Add note',
  'Add to order': 'Add to order',
  'All menu': 'All menu',
  'All status': 'All status',
  'Already Ordered? Track the order here.': 'Already Ordered?\nTrack the order here.',
  'Are you sure want to cancel order?': 'Are you sure want to cancel order?',
  'Available promo': 'Available promo',
  'Birth date': 'Birth date',
  'Cancel': 'Cancel',
  'Canceled': 'Canceled',
  'Change PIN': 'Change PIN',
  'Change language': 'Change language',
  'Change': 'Change',
  'Choose discount': 'Choose discount',
  'Choose level': 'Choose level',
  'Choose topping': 'Choose topping',
  'Choose voucher': 'Choose voucher',
  'Completed': 'Completed',
  'Connected to the internet': 'Connected to the internet',
  'Continue to sign in': 'Continue to sign in',
  'Create note': 'Create note',
  'Delete from order': 'Delete from Order',
  'Detail menu': 'Detail menu',
  'Detail voucher': 'Detail voucher',
  'Device info': 'Device Info',
  'Discount can not be combined': 'Discount can not be combined',
  'Discount': 'Discount',
  'Distance not close': 'Distance not close',
  'Drink': 'Drink',
  'Email is not valid': 'Email is not valid',
  'Email or password is incorrect': 'Email or password is incorrect',
  'Email': 'Email',
  'Empty cart': 'Empty cart',
  'Enter PIN code': 'Enter PIN code',
  'Error': 'Error',
  'Fingerprint not available': 'Fingerprint not available',
  'Food': 'Food',
  'Get this promo': 'Get this promo! Access this link\n@link',
  'Give rating': 'Give rating',
  'History': 'History',
  'Home Page': 'Home Page',
  'Home': 'Home',
  'In queue': 'In queue',
  'Info discount': 'Info discount',
  'Level': 'Level',
  'Loading...': 'Loading...',
  'Location permission not granted forever': 'Location permission not granted forever',
  'Location permission not granted': 'Location permission not granted',
  'Location service not enabled': 'Location service not enabled',
  'Log out': 'Log out',
  'Login with': 'Login with',
  'Login': 'Login',
  'More info': 'More info',
  'Name is required': 'Name is required',
  'Name': 'Name',
  'No data': 'No data',
  'No discount': 'No discount',
  'No': 'No',
  'Not connected to the internet': 'Not connected to the internet',
  'Note': 'Note',
  'Okay': 'Okay',
  'On going': 'On going',
  'Open settings': 'Open settings',
  'Order accepted': 'Order accepted',
  'Order again': 'Order again',
  'Order completed': 'Order completed',
  'Order is being prepared': 'Order is being prepared',
  'Order now': 'Order now',
  'Order': 'Order',
  'PIN already wrong 3 times. Please try again later.': 'PIN already wrong 3 times. Please try again later.',
  'PIN must be 6 digits long': 'PIN must be 6 digits long',
  'PIN wrong! n chances left.': 'PIN wrong! @n chances left.',
  'Password is required': 'Password is required',
  'Password': 'Password',
  'Payment': 'Payment',
  'Phone number is required': 'Phone number is required',
  'Phone number must be at least 10 characters': 'Phone number must be at least 10 characters',
  'Phone number': 'Phone number',
  'Please authenticate to confirm order': 'Please authenticate to confirm order',
  'Please take your order': 'Please take your order',
  'Preparing': 'Preparing',
  'Press your fingerprint': 'Press your fingerprint',
  'Price': 'Price',
  'Profile': 'Profile',
  'Promo': 'Promo',
  'Ready': 'Ready',
  'Review now': 'Review now',
  'Review': 'Review',
  'Search': 'Search',
  'Searching location...': 'Searching location...',
  'Server error': 'Server error. Please try again later.',
  'Something went wrong': 'Something went wrong',
  'Start placing orders.': 'Start placing orders.',
  'Success!': 'Success!',
  'Terms and conditions': 'Terms and conditions',
  'The food you ordered will appear here so you can find your favorite menu again!': 'The food you ordered will appear here so you can find your favorite menu again!',
  'The use of vouchers cannot be combined with a discount': 'The use of vouchers cannot be combined with a discount',
  'Topping': 'Topping',
  'Total orders': 'Total orders',
  'Total payment': 'Total payment',
  'Unknown error': 'Unknown error',
  'Unknown location': 'Unknown location',
  'Update PIN': 'Update PIN',
  'Update to order': 'Update to Order',
  'Use voucher later': 'Use voucher later',
  'Use voucher': 'Use voucher',
  'Valid date': 'Valid date',
  'Verify order': 'Verify order',
  'Verify using PIN code': 'Verify using PIN code',
  'Verify your ID card now!': 'Verify your ID card now!',
  'Version': 'Version',
  'Voucher': 'Voucher',
  'Warning': 'Warning',
  'Yes': 'Yes',
  'You can track your order in order history': 'You can track your order in order history',
  'You have verified your ID card': 'You have verified your ID card',
  'Your order has been canceled': 'Your order has been canceled',
  'diskon': 'Discount',
  'employee reward program': 'employee reward program',
  'or': 'or',
  'voucher': 'Voucher',
};