// @formatter:off
// ignore_for_file: constant_identifier_names

const Map<String, String> translations_id_ID = {
  'Account info': 'Info akun',
  'Add note': 'Tambahkan catatan',
  'Add to order': 'Tambahkan ke pesanan',
  'All menu': 'Semua menu',
  'All status': 'Semua status',
  'Already Ordered? Track the order here.': 'Sudah Pesan?\nLacak pesananmu di sini.',
  'Available promo': 'Promo yang tersedia',
  'Birth date': 'Tanggal lahir',
  'Canceled': 'Dibatalkan',
  'Change PIN': 'Ubah PIN',
  'Change language': 'Ganti bahasa',
  'Change': 'Ubah',
  'Choose discount': 'Pilih diskon',
  'Choose level': 'Pilih level',
  'Choose topping': 'Pilih toping',
  'Choose voucher': 'Pilih voucher',
  'Completed': 'Sudah diambil',
  'Connected to the internet': 'Terhubung ke internet',
  'Continue to sign in': 'Masuk untuk melanjutkan!',
  'Create note': 'Buat catatan',
  'Delete from order': 'Hapus dari pesanan',
  'Detail menu': 'Detail menu',
  'Detail voucher': 'Detail voucher',
  'Device info': 'Info perangkat',
  'Discount can not be combined': 'Diskon tidak dapat digabung',
  'Discount': 'Diskon',
  'Distance not close': 'Jarak tidak dekat dengan Java Code',
  'Drink': 'Minuman',
  'Email or password is incorrect': 'Email atau kata sandi salah',
  'Email': 'Email',
  'Empty cart': 'Keranjang kosong',
  'Enter PIN code': 'Masukkan PIN',
  'Error': 'Terjadi kesalahan',
  'Fingerprint not available': 'Fingerprint tidak tersedia',
  'Food': 'Makanan',
  'Get this promo': 'Dapatkan promo ini! Akses link berikut\n@link',
  'Give rating': 'Beri penilaian',
  'History': 'Riwayat',
  'Home Page': 'Halaman utama',
  'Home': 'Beranda',
  'In queue': 'Dalam antrian',
  'Info discount': 'Info diskon',
  'Level': 'Level',
  'Loading...': 'Memuat...',
  'Location permission not granted forever': 'Izin lokasi tidak diberikan secara permanen.',
  'Location permission not granted': 'Izin lokasi tidak diberikan.',
  'Location service not enabled': 'Layanan lokasi dimatikan.',
  'Log out': 'Keluar',
  'Login with': 'Masuk menggunakan',
  'Login': 'Masuk',
  'More info': 'Info lainnya',
  'Name': 'Nama',
  'No data': 'Tidak ada data',
  'No discount': 'Tidak ada diskon',
  'Not connected to the internet': 'Tidak terhubung ke internet',
  'Note': 'Catatan',
  'Okay': 'Oke',
  'On going': 'Sedang berjalan',
  'Open settings': 'Buka pengaturan',
  'Order accepted': 'Pesanan diterima',
  'Order again': 'Pesan lagi',
  'Order completed': 'Pesanan selesai',
  'Order is being prepared': 'Pesanan sedang diproses',
  'Order now': 'Pesan sekarang',
  'Order': 'Pesanan',
  'PIN already wrong 3 times. Please try again later.': 'PIN salah 3 kali. Silahkan coba lagi nanti.',
  'PIN must be 6 digits long': 'PIN harus 6 digit',
  'PIN wrong! n chances left.': 'PIN salah! Sisa @n kesempatan.',
  'Password': 'Kata Sandi',
  'Payment': 'Pembayaran',
  'Phone number': 'No. telepon',
  'Please authenticate to confirm order': 'Harap otentikasi untuk konfirmasi pesanan',
  'Please take it': 'Silahkan diambil',
  'Preparing': 'Sedang siapkan',
  'Press your fingerprint': 'Tekan fingerprint Anda',
  'Price': 'Harga',
  'Profile': 'Profil',
  'Promo': 'Promo',
  'Ready': 'Bisa diambil',
  'Review now': 'Nilai Sekarang',
  'Review': 'Penilaian',
  'Search': 'Pencarian',
  'Searching location...': 'Mencari lokasimu...',
  'Server error': 'Kesalahan server. Silahkan coba lagi nanti.',
  'Something went wrong': 'Terjadi kesalahan',
  'Start placing orders.': 'Mulai buat pesanan.',
  'Terms and conditions': 'Syarat dan ketentuan',
  'The food you ordered will appear here so you can find your favorite menu again!': 'Makanan yang kamu pesan akan muncul di sini agar kamu bisa menemukan menu favoritmu lagi!',
  'The use of vouchers cannot be combined with a discount': 'Penggunaan voucher tidak dapat digabung dengan diskon',
  'Topping': 'Toping',
  'Total orders': 'Total pesanan',
  'Total payment': 'Total pembayaran',
  'Unknown error': 'Kesalahan tidak diketahui',
  'Unknown location': 'Lokasi tidak diketahui',
  'Update PIN': 'Perbarui PIN',
  'Update to order': 'Perbarui ke pesanan',
  'Use voucher later': 'Pakai voucher nanti',
  'Use voucher': 'Pakai voucher',
  'Valid date': 'Tanggal valid',
  'Verify order': 'Verifikasi pesanan',
  'Verify using PIN code': 'Verifikasi menggunakan PIN',
  'Verify your ID card now!': 'Verifikasi KTP mu sekarang!',
  'Version': 'Versi',
  'Voucher': 'Voucher',
  'You can track your order in order history': 'Kamu dapat melacak pesananmu di fitur Pesanan',
  'You have verified your ID card': 'Kamu sudah verifikasi KTP',
  'diskon': 'Diskon',
  'employee reward program': 'employee reward program',
  'or': 'atau',
  'voucher': 'Voucher',
};